export const photoSeeds = [
    {
        filename: "herb_001.jpg",
        originalName: "กระเพรา.jpg",
        path: "/uploads/herbs/herb_001.jpg",
        url: "https://example.com/uploads/herbs/herb_001.jpg",
        mimeType: "image/jpeg",
        size: 245760,
        alt: "รูปภาพกระเพรา",
        description: "ใบกระเพราสีเขียวสด",
        herbId: 1,
        familyId: 1,
        villageId: 1
    },
    {
        filename: "herb_002.jpg",
        originalName: "โหระพา.jpg",
        path: "/uploads/herbs/herb_002.jpg",
        url: "https://example.com/uploads/herbs/herb_002.jpg",
        mimeType: "image/jpeg",
        size: 198432,
        alt: "รูปภาพโหระพา",
        description: "ใบโหระพาสีเขียวอ่อน",
        herbId: 2,
        familyId: 1,
        villageId: 1
    },
    {
        filename: "herb_003.jpg",
        originalName: "แมงลัก.jpg",
        path: "/uploads/herbs/herb_003.jpg",
        url: "https://example.com/uploads/herbs/herb_003.jpg",
        mimeType: "image/jpeg",
        size: 312576,
        alt: "รูปภาพแมงลัก",
        description: "ใบแมงลักสีเขียวเข้ม",
        herbId: 3,
        familyId: 1,
        villageId: 2
    },
    {
        filename: "family_001.jpg",
        originalName: "วงศ์กะเพรา.jpg",
        path: "/uploads/families/family_001.jpg",
        url: "https://example.com/uploads/families/family_001.jpg",
        mimeType: "image/jpeg",
        size: 156789,
        alt: "รูปภาพวงศ์ Lamiaceae",
        description: "ตัวอย่างพืชในวงศ์กะเพรา",
        familyId: 1
    },
    {
        filename: "village_001.jpg",
        originalName: "หมู่บ้านสมุนไพร.jpg",
        path: "/uploads/villages/village_001.jpg",
        url: "https://example.com/uploads/villages/village_001.jpg",
        mimeType: "image/jpeg",
        size: 445632,
        alt: "รูปภาพหมู่บ้าน",
        description: "สวนสมุนไพรในหมู่บ้าน",
        villageId: 1
    },
    {
        filename: "herb_004.png",
        originalName: "ขิง.png",
        path: "/uploads/herbs/herb_004.png",
        url: "https://example.com/uploads/herbs/herb_004.png",
        mimeType: "image/png",
        size: 387456,
        alt: "รูปภาพขิง",
        description: "รากขิงสีเหลือง",
        herbId: 4,
        familyId: 29,
        villageId: 2
    },
    {
        filename: "herb_005.jpg",
        originalName: "ข่า.jpg",
        path: "/uploads/herbs/herb_005.jpg",
        url: "https://example.com/uploads/herbs/herb_005.jpg",
        mimeType: "image/jpeg",
        size: 298765,
        alt: "รูปภาพข่า",
        description: "รากข่าสีขาว",
        herbId: 5,
        familyId: 29,
        villageId: 3
    },
    {
        filename: "herb_006.jpg",
        originalName: "ตะไคร้.jpg",
        path: "/uploads/herbs/herb_006.jpg",
        url: "https://example.com/uploads/herbs/herb_006.jpg",
        mimeType: "image/jpeg",
        size: 234567,
        alt: "รูปภาพตะไคร้",
        description: "ต้นตะไคร้สีเขียว",
        herbId: 6,
        familyId: 8,
        villageId: 1
    }
];